server:
  port: 8080

spring:
  application:
    name: n-plus-one
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/nplusone
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  #  datasource:
  #    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database: mysql
    defer-datasource-initialization: true
    properties:
      hibernate:
#        format_sql: true
        show_sql: true

# jpa logging ? ??
#logging:
#  level:
#    org.hibernate.type.descriptor.sql: trace