spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true # 자동으로 entity 에서 활용하는 테이블을 생성
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_manager
    username: root
    password: 413730
server:
  port: 8080
logging:
  level:
    root: info