spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
  #    url: jdbc:mysql://localhost/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
  #    username: root
  #    password: 413730
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      data-locations: classpath:person.sql
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true