### GET Server hello Object
GET http://localhost:8080/api/client/hello/object

### GET Server hello Entity
GET http://localhost:8080/api/client/hello/entity

### GET Server hello User Entity
GET http://localhost:8080/api/client/hello/entity/user

### GET Server hello User Entity
GET http://localhost:8080/api/client/hello/entity/user/params

### POST server userpost
GET http://localhost:8080/api/client/hello/user/post

### POST server userpost exchage
GET http://localhost:8080/api/client/exchange

### POST server userpost generic exchage
GET http://localhost:8080/api/client/exchange/generic