spring:
  application:
    name: redis-starter
  session:
    redis:
      namespace: spring:session
      flush-mode: on-save
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379